language: go
go_import_path: github.com/apoloa/bjournal
go:
  - "1.17"

jobs:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: ppc64le
    - os: osx
      arch: amd64

dist: trusty
sudo: false

install: true

script:
  - go build
  - go test ./...